### ISSUE TITLE
`/images.json' are the same file

### ISSUE THREAD

**Issue by soichih** [brain-life/app-LIFE_AFQ_qualitycheck#2]
I am seeing following error message.

```
MATLAB numerical calculation framework version 2017a loaded.
cp: '/N/dc2/scratch/hayashis/dev1-carbonate-workflows/59df8c6363b8bc48cc44ad6a/59df8c63cb23b348d2c5978f/images.json' and './images.json' are the same file
{Reference to non-existent field 'classified_streams_count'.

Error in feAndAFQqualityCheck (line 159)
        results.AFQstats.validated.classified_stream_proportion=results.AFQstats.validated.classified_streams_count/results.LiFEstats.WBFG.stream_count;
        
Error in main (line 23)
[figure, results] = feAndAFQqualityCheck(fe, classification, 'images')
} 
```

**Comment by kitchell** [comment]
I assume this is because the whole git repository is now in the working dir? or are you rerunning it and it is not removed before rerunning?

**Comment by kitchell** [comment]
I updated it to remove images.json at the start.

**Comment by soichih** [comment]
@kitchell Thanks. Now I am seeing a slightly different error message.

```
cp: cannot stat '/N/dc2/scratch/hayashis/dev1-carbonate-workflows/59df8c6363b8bc48cc44ad6a/59df8c63cb23b348d2c5978f/images.json': No such file or directory
{Reference to non-existent field 'classified_streams_count'.
```

I was running a fresh run, but yes, I see `images.json` stored as part of the git repo, and that might be interfering but I am not sure.

**Comment by kitchell** [comment]
are you using an AFQ that was removed before or after?

**Comment by kitchell** [comment]
that is for the second error there, i misread

**Comment by kitchell** [comment]
it is trying to copy the file from the service dir. does the service dir no longer contain the git repo?

**Comment by kitchell** [comment]
Maybe it does not need to copy it anymore if the git repo is in the output folder

**Comment by soichih** [comment]
Ah.. I see what you are doing with images.json

$SERVICE_DIR still exists for backward compatibility , but it just points to $CWD.. You should get rid of the references to $SERVIDE_DIR as you come across.

So this line

> cp $SERVICE_DIR/images.json .

Is basically copying the images.json to/from the same directory. You should remove this.

And on start.sh, you shouldn't remove the images.json - since it's used as part of output although it comes with your repo itself.

**Comment by kitchell** [comment]
ok I fixed that. try it now
